---
- hosts: consul-servers,consul-agents
  gather_facts: yes
  remote_user: ubuntu
  become: yes

  vars:
    _consul_url: https://releases.hashicorp.com/consul/1.4.4/consul_1.4.4_linux_amd64.zip

  tasks:
    - name: setup consul user
      group:
        name: consul
        system: yes

    - user:
        name: consul
        shell: /sbin/nologin
        group: consul
        system: yes

    - name: get consul
      get_url:
        dest: "{{ playbook_dir }}/tmp/consul.zip"
        url: "{{ _consul_url }}"
      delegate_to: 127.0.0.1
      become: no
      run_once: yes

    - file:
        dest: "{{ item }}"
        state: directory
      with_items:
        - /opt/bin

    - file:
        dest: "{{ item }}"
        state: directory
        owner: consul
        group: consul
        mode: 0775
      with_items:
        - /var/lib/consul
        - /etc/consul.d

    - unarchive:
        src: "{{ playbook_dir }}/tmp/consul.zip"
        dest: /opt/bin

    - name: prep system start script
      copy:
        src: "{{ playbook_dir }}/config/consul.service"
        dest: /etc/systemd/system/consul.service
